### ISSUE TITLE
error when compile the array_laserbeamFoam

### ISSUE THREAD

**Issue by wangdz99** [micmog/LaserbeamFoam#17]
g++ -std=c++14 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -Ilaserarray/lnInclude -IincompressibleInterPhaseTransportModel/lnInclude -I/opt/openfoam10/src/physicalProperties/lnInclude -I/opt/openfoam10/src/twoPhaseModels/twoPhaseMixture/lnInclude -I/opt/openfoam10/src/twoPhaseModels/interfaceProperties/lnInclude -I/opt/openfoam10/src/twoPhaseModels/incompressibleTwoPhaseMixture/lnInclude -I/opt/openfoam10/src/twoPhaseModels/immiscibleIncompressibleTwoPhaseMixture/lnInclude -I/opt/openfoam10/src/twoPhaseModels/twoPhaseChange/lnInclude -I/opt/openfoam10/src/MomentumTransportModels/momentumTransportModels/lnInclude -I/opt/openfoam10/src/MomentumTransportModels/incompressible/lnInclude -I/opt/openfoam10/src/MomentumTransportModels/phaseIncompressible/lnInclude -I/opt/openfoam10/src/meshTools/lnInclude -I/opt/openfoam10/src/finiteVolume/lnInclude -I/opt/openfoam10/src/meshTools/lnInclude -I/opt/openfoam10/src/sampling/lnInclude -IlnInclude -I. -I/opt/openfoam10/src/OpenFOAM/lnInclude -I/opt/openfoam10/src/OSspecific/POSIX/lnInclude   -fPIC -fuse-ld=bfd -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/array_laserbeamFoam.o -L/opt/openfoam10/platforms/linux64GccDPInt32Opt/lib \
    -limmiscibleIncompressibleTwoPhaseMixture -ltwoPhaseChangeModels -lmomentumTransportModels -lincompressibleMomentumTransportModels -lincompressibleInterPhaseTransportModel -lfiniteVolume -lfvModels -lfvConstraints -lmeshTools -L/root/OpenFOAM/root-10/platforms/linux64GccDPInt32Opt/lib -larray_laserbeamFoam -lOpenFOAM -ldl  \
     -lm -o /root/OpenFOAM/root-10/platforms/linux64GccDPInt32Opt/bin/array_laserbeamFoam
/usr/bin/ld.bfd: cannot find -larray_laserbeamFoam
collect2: error: ld returned 1 exit status
/opt/openfoam10/wmake/makefiles/general:152: recipe for target '/root/OpenFOAM/root-10/platforms/linux64GccDPInt32Opt/bin/array_laserbeamFoam' failed
make: *** [/root/OpenFOAM/root-10/platforms/linux64GccDPInt32Opt/bin/array_laserbeamFoam] Error 1

**Comment by tomflint22** [comment]
Did you run the ./Allwclean then the ./Allwmake scripts?

You need to build the library first, it looks like you just ran wclean wmake

**Comment by tomflint22** [comment]
Please just run:
./Allwclean

then:
./Allwmake

scripts then you won't have this issue. Thanks,

Tom

**Comment by wangdz99** [comment]
In facte, after I delete the last two lines in the solver/arrau_laserbeamFoam/make/options. It can run.
It might not link itself as EXE_lIBS during compling.

**Comment by wangdz99** [comment]
Hi Tom,
In facte, after I delete the last two lines in the solver/arrau_laserbeamFoam/make/options. It can run.
It might not link itself as EXE_lIBS during compling.
Dianzheng

**Comment by tomflint22** [comment]
Dont delete the last 2 lines. These tell the solver how to define the laser objects using the class structure. You just need to run the ./Allclean then ./Allmake scripts. 

What output do you get when you run ./Allmake?

**Comment by wangdz99** [comment]
It report an error:

_usr/bin/ld.bfd: cannot find -larray_laserbeamFoam
collect2: error: ld returned 1 exit status
/opt/openfoam10/wmake/makefiles/general:152: recipe for target '/root/OpenFOAM/root-10/platforms/linux64GccDPInt32Opt/bin/array_laserbeamFoam' failed
make: *** [/root/OpenFOAM/root-10/platforms/linux64GccDPInt32Opt/bin/array_laserbeamFoam] Error 1_

**Comment by tomflint22** [comment]
So that is an error from building the solver. If you look in the Allmake script there should be 3 lines. Can you try running each line individually and letting me know what output you get.

**Comment by wangdz99** [comment]
e.....I made a mistake. Now it can work alright. Just ./Allwmake is ok. Thanks, Tom!

**Comment by tomflint22** [comment]
No Problem. Happy to help.

That solver you are compelling is the new multi-laser solver. I only have 1 test case for that so far, but in the laser properties file you can set the properties for each laser individually. Most people wipe probably want all the properties the same except for the b_g and l_g values to make a laser array. Have a play around and let me know if you need any more help with anything.

All the best,

Tom

**Comment by tomflint22** [comment]
I have the multi-component version of the code finished too. I just need to neaten up the tutorial cases and then that will be released as LaserbeamFoam -V2, if that is of interest too.

**Comment by wangdz99** [comment]
Good job. It will help my research work.
