### ISSUE TITLE
Some problems in the Plate3D examples

### ISSUE THREAD

**Issue by micheleiacopo** [micmog/LaserbeamFoam#20]
Hello, 
Thanks for this new contribution.

I was trying the new laserBeamFoam solver via the Plate3D/Plate3D_2 tutorial and I'm having errors while running it:
- the Plate3D example crashes at solution time because of at least some missing properties in the physicalProperties.metal file (first error is "poly_kappa" missing)
- the Plate3D_2 example crashes at setField time because of missing conditions on the "right" and "left" patches

Comparing the corresponding files in the two folders (and comparing them to the 2D case too), various differences can be found, apart from, evidently, the angle of the laser. Most likely these are all errors coming from the conversion from the 2D case and/or adaptations from a previous version of the solver.

**Comment by tomflint22** [comment]
Hi,

you can just copy the poly_kappa and poly_cp from another example to get these to run. These are from the old version before we added the polynomial thermal properties. When I get time I'll fix these tutorials, but I'm very busy at the moment.
