### ISSUE TITLE
Tutorial results for Plate2D match?

### ISSUE THREAD

**Issue by hongluck** [micmog/LaserbeamFoam#24]
Thanks for the great work. 
Going back and fourth with your paper in SoftwareX (laserbeamFoam: Laser ray-tracing and thermally induced state
transition simulation toolkit) to learn your work.
I was running some tutorials of your code but could not reproduce the penetration that should happen in 0.03s.
(First example, Plate2D)
Is the code modified after the publication or is it just me not able to reproduce the work
Thanks in advance.

**Comment by tomflint22** [comment]
Hi,

Yes we've changed a lot of the inputs considerable from the paper. Now you can have temperature dependant thermal properties and specify the laser radius in different ways. What has probably happened is that the properties have been updated to be temperature dependant when in the simulations for the paper they were constant.
A lot of people are using the code now and seeing good agreement with  experiment so we know the code is correct. Those cases for the paper were just to show the functionality really.

**Comment by hongluck** [comment]
Thanks for the quick and comprehensive response.
I was just wondering what I was doing wrong.
Thanks again for sharing your code so that many researchers can learn and
use!

2024년 3월 29일 (금) 오후 11:10, Tom Flint ***@***.***>님이 작성:
