### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by DasarathanSampath** [micmog/LaserbeamFoam#25]
When I compile the laserbeamFoam solver, I get the below error.
Make/linux64GccDPInt32Opt/files:1: *** missing separator. Stop.
I guess the make files are not saved in Linux.

**Comment by tomflint22** [comment]
Hi,

Did you manage to sort this out? I've not seen this issue before. I also see you've sent me an email which seems like you've compiled the code now?

**Comment by DasarathanSampath** [comment]
Hi,

Thanks for your email.

I have fixed it. I just recreated the files inside the Make folder in the
Linux terminal using the Nano editor, and it compiled without error.

Thanks
Dasarathan
