### ISSUE TITLE
Slow temperature rise in 2D model using multi-laser slover 

### ISSUE THREAD

**Issue by HaijieCHANG** [micmog/LaserbeamFoam#27]
Hello,

It was a pleasure to get in touch with you.
I am having problems with the ArraylaserbeamFoam solver. In a 2D model using ArraylaserbeamFoam, the model heats up very slowly. I am using a heat source of two 1200W lasers with 0.5mm radius. The temperature at 0.015s is only 820k as shown below.

![image](https://github.com/micmog/LaserbeamFoam/assets/148329470/2e991304-55b6-4c4f-966c-f86c66276fb9)

But in the similar 2D model with MultiComponentlaserbeanFoam solver, the heat source is one 1200W laser with 0.5mm radius. The temperature at 0.015s is 3000k as shown below.

![image](https://github.com/micmog/LaserbeamFoam/assets/148329470/1eb0ac0d-d79c-44c8-accb-756ad187d554)

The model files have been attached, the multi-laser model is using ArraylaserbeamFoam and the single laser model is using MultiComponentlaserbeanFoam.

[ProblemCases.zip](https://github.com/user-attachments/files/16131188/ProblemCases.zip)

Your help in solving this problem would be greatly appreciated!
Thank you in advance and best regards,

**Comment by tomflint22** [comment]
Hi,

thanks for finding this. The issue was that in the multiComponentLaserbeamFoam solver, the Radius_Flavour was not being read, and this was hard-coded to 2.0. So it was a different distribution between the 2 cases you were comparing. I have fixed this now and you can specify this 'flavour' in both solvers

**Comment by tomflint22** [comment]
Sorry - my mis-understanding. I see now it was the array solver that had the issue. I'll look into this ASAP

**Comment by tomflint22** [comment]
Hi Haijie,

I just looked at this again, when I run the laserbeamFoam solver and the array_laserbeamFoam solver (with just 1 source) on the same case I get the exact same answer (as expected). You can verify this by running the Plate2D tutorial with laserbeamFoam, and the Plate2D_arraytest tutorial (in the array_laserbeamFoam sub-directory in tutorials) with array_laserbeamFoam. So I think I can close this issue now. 

I think this was down to the different radius_flavours in your initial cases as this was not implemented in the multi-component solver.

I'll close this, but feel free to message me or raise issues if you see anything else.
